[build]
  base = "edtech-social-app"
  command = "npm run build"
  publish = "edtech-social-app/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/register"
  status = 302
